services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tada-backend-stage
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env.stage
    command: node dist/main.js
    networks:
      - rental_network_stage
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rental_network_stage:
